### PR TITLE
Adding kubejobs unit tests and solving tox problem

### PR DESCRIPTION
**Pull request by javanlacerda**
- add kubejobs unit tests
- add pytest and mock to requirements

### CODE REVIEW

**Comment by javanlacerda** [comment]
This pull request has many commits, but is able of squash and merge.

**Comment by clenimar** [comment]
it looks good to me, although it's a bit odd to have that many unrelated commits in the PR. can you edit it to include just the commits that are relevant to this specific change? thanks.

**Comment by rafaelvfalc** [comment]
I tried to run the tests via 'tox -epy27' command in a brand new virtual machine and all test cases of the file 'monitor/tests/plugins/kubejobs/test_plugin.py' failed. 

I also agree with @clenimar comment about the unrelated commits. The commits of the PR needs to represent the changes made in the code. 'squash' may help to solve this issue.

**Comment by javanlacerda** [comment]
I'll close this pr because is better open other with all problems solved.

**Pull request closed without merging**
